MigrationとModelを作成
kaikitano0610/tweet-place pull request #1
Opened 2024-08-21 07:01 UTC by kaikitano0610

2024-08-21 07:05 UTC, ayasamind requested changes
色々コメントしてます！

2024-08-21 07:05 UTC, ayasamind commented on app/Models/Comment.php
> +        'text'
user_idも必要じゃないかな？

2024-08-21 07:05 UTC, ayasamind commented on app/Models/Comment.php
> +    public function user()
せっかくだし返り値の型を書くようにしてみよっか！
https://qiita.com/yusuke_mrmt/items/b2d0ddf1f62be080acbc#%E6%88%BB%E3%82%8A%E5%80%A4%E3%81%AE%E5%9E%8B%E5%AE%A3%E8%A8%80

2024-08-21 07:05 UTC, ayasamind commented on app/Models/Favorite.php
> +    public $timestamps = false;
これtiimestamps = falseにしてる理由ってなんだろ？

2024-08-21 07:05 UTC, ayasamind commented on app/Models/Follower.php
> +    public $incrementing = false;
こちらも！なんでそうするんだっけ？

2024-08-21 07:05 UTC, ayasamind commented on app/Models/Favorite.php
> +    public $timestamps = false;
あとここはfillable必要ない？

2024-08-21 07:05 UTC, ayasamind commented on app/Models/Tweet.php
> +        return $this->hasMany(Comment::class);
同じく返り値の型を！
fillableもtextだけじゃなさそうな気がする

2024-08-21 07:05 UTC, ayasamind commented on app/Models/User.php
> +    }
同上

2024-08-23 01:00 UTC, kaikitano0610 commented on app/Models/Favorite.php
> +    public $timestamps = false;
いいねをした時間は必要ないから、Migrationからもtimestampsを消しており、ModelではデフォルトでTimestampが設定されているのでfalseにしているとありました！

2024-08-23 04:35 UTC, kaikitano0610 commented on app/Models/Comment.php
> +        'text'
guardedで書き換えました！

2024-08-23 07:14 UTC, ayasamind approved these changes
LGTMです！

2024-08-23 07:14 UTC, ayasamind commented on app/Models/Favorite.php
> +    public $timestamps = false;
なるほど！承知！

2024-08-23 07:16 UTC, merged